version: "3.5"
services:
  api1: &api1
    build: .
    restart: always
    expose:
      - "3333"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      REDIS_URL: redis://redis:6379
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "0.5GB"

  api2:
    <<: *api1
    
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "1GB"

  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "0.5GB"

  redis:
    image: redis:alpine
    command: redis-server --save "" --appendonly no
    expose:
      - "6379"
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "0.5GB"